### ISSUE TITLE
job doesn't leave queue on TSCC

### ISSUE THREAD

**Issue by aryarm** [mkandes/galyleo#9]
Hi @mkandes,

Thanks for creating such a useful tool! I am really looking forward to using this on a day to day basis.

I've been having some trouble with it, and I'm wondering if you might have any suggestions. Basically, the notebook job never seems to leave the queue. I'm running on TSCC with the following command:
```
galyleo launch --account amassara --partition home-gymrek --cpus 1 --memory 2 --time-limit 00:30:00 --conda-env jupyter --conda-init /home/amassara/miniconda3/etc/profile.d/conda.sh
```
I've installed jupyter lab in a conda environment named `jupyter`. The `galyleo launch` command seems to work fine, but when I navigate to the webpage that it gives me, it just says that it's been submitted to the queue. It never leaves the queue after that.
I was worried that this was just because the queue was overwhelmed, so I tried to submit another job to the queue with a longer requested walltime. The longer job got executed but the notebook job never did. Also, I looked to see if there were any other jobs queued up at the time, and there weren't.

I would appreciate any suggestions you might be able to give.

**Also, quick question:** Does the `-A` option refer to our own account username? Or should that be the lab's ID, like `gymreklab` or something similar?

**Comment by mkandes** [comment]
Hi @aryarm - Yes, the `--account` or `-A` option refers to the name of your lab's allocation ID, which you can get on TSCC from the `gbalance` command.

```
[mkandes@tscc-login1 ~]$ gbalance -u amassara
Id   Name            Amount  Reserved Balance CreditLimit Available 
---- --------------- ------- -------- ------- ----------- --------- 
82   yeo-group       2880518    23522 2856996           0   2856996 
1189 gymreklab-group  301474     1016  300458           0    300458 
[mkandes@tscc-login1 ~]$
```

So, in this case, since you're submitting to your home partition for the gymrek lab, you'll want to set `--account gymreklab-group`.  The reason the job is waiting in the queue is because of your initially incorrect `--account amassara`  setting. Simply `qdel` the job and resubmit a new one with `--account gymreklab-group`.

**Comment by aryarm** [comment]
perfect; it works!

thank you so much!

The `gbalance` suggestions was very helpful. If it isn't TSCC-specific, other users might also appreciate it being in the Quick Start within the `README.md`.

**Comment by mkandes** [comment]
@aryarm - I believe `glanace` is Maui/Torque command. So, its not necessarily TSCC-specific. But yes, this is the only scheduler of this type we have left at SDSC. I'll try and make it more clean in the `README.md` that this is not your username ... but the account name/ID you would use with the `-A` option in any normal batch job script.
